---
title: "Chapter 1 Analysis"
format: html
editor: visual
---

# **Anthropogenic fear differs in mechanisms and magnitude across ecosystems and trophic levels.**

```{r}
#import libraries

library(ggplot2)
library(dplyr)
library(tidyr)

#set ggplot theme

theme_set(theme_bw()+
            theme(text = element_text(size = 20),
                  legend.position = "top")
          )

```

## Initial Screening

```{r}
# import data

initial_screening <- read.csv("data/chapter-1_initial-screening_manya.csv")

head(initial_screening)
```

```{r}
summary(initial_screening)
```

### Number of papers accepted

```{r}
length(initial_screening$key)
```

### Distribution of papers by year

```{r fig.height=4.5, fig.width=8}
ggplot(data = initial_screening, aes(year))+
  geom_histogram(binwidth = 2)+
  labs(x = "Year of Publicaiton", y = "Number of publicaitons")
```

### Exposure

```{r fig.height=8, fig.width=8}
exposure <- initial_screening%>%
  group_by(exposure)%>%
  count()%>%
  filter(exposure != "")

library(wordcloud)

suppressWarnings(
wordcloud(word = exposure$exposure, freq = exposure$n, min.freq = 1,           max.words=200, random.order=FALSE, rot.per=0.35,            colors=brewer.pal(8, "Dark2"))
)
```

### Populations

```{r fig.height=8, fig.width=8}
population <- initial_screening%>%
  group_by(population)%>%
  count()%>%
  filter(population != "")

suppressWarnings(
wordcloud(word = population$population, freq = population$n, min.freq = 1,           max.words=200, random.order=FALSE, rot.per=0.35,            colors=brewer.pal(8, "Dark2"))
)
```

### Control

```{r fig.height=8, fig.width=8}
control <- initial_screening%>%
  group_by(control)%>%
  count()%>%
  filter(control != "", control != "-")

suppressWarnings(
wordcloud(word = control$control, freq = control$n, min.freq = 1,           max.words=200, random.order=FALSE, rot.per=0.35,            colors=brewer.pal(8, "Dark2"))
)
```

Number of studies with a control:

```{r fig.height=8, fig.width=8}

initial_screening%>%
  filter(control != "", control != "-")%>%
  count()%>%
  as.numeric()
```

### Outcomes

```{r fig.height=8, fig.width=8}

outcome <- initial_screening%>%
  group_by(outcome)%>%
  count()%>%
  filter(outcome != "")

suppressWarnings(
wordcloud(word = outcome$outcome, freq = outcome$n, min.freq = 1,           max.words=200, random.order=FALSE, rot.per=0.35,            colors=brewer.pal(8, "Dark2"))
)
```
